apiVersion: v1
kind: Pod
metadata:
  name: ngsa-cosmos
  labels:
    app: ngsa-cosmos

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: ghcr.io/retaildevcrews/ngsa-app:beta

    args:
      - --prometheus
      - --log-level
      - Warning
      - --request-log-level
      - Information
      - --zone
      - dev
      - --region
      - dev

    ports:
    - containerPort: 8080

    volumeMounts:
    - name: secrets
      mountPath: "/app/secrets"

  volumes:
  - name: secrets
    secret:
      secretName: ngsa-secrets
      defaultMode: 444

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-cosmos
  labels:
    app: ngsa-cosmos

spec:
  type: NodePort
  selector:
    app: ngsa-cosmos
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
