apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
      svc: web
  template:
    metadata:
      labels:
        env: production
        svc: web
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
