apiVersion: v1
kind: Pod

metadata:
  name: loderunner-baseline-cosmos
  labels:
    app: loderunner-baseline-cosmos

spec:
  restartPolicy: Never
  containers:
  - name: app
    image: ghcr.io/retaildevcrews/ngsa-lr:beta
    imagePullPolicy: Always

    args:
    - -s
    - http://ngsa-cosmos:8080
    - -f
    - baseline.json
    - --prometheus
    - --zone
    - dev
    - --region
    - dev
