apiVersion: v1
kind: Pod

metadata:
  name: loderunner-benchmark-cosmos
  labels:
    app: loderunner-benchmark-cosmos

spec:
  restartPolicy: Always
  containers:
  - name: app
    image: ghcr.io/retaildevcrews/ngsa-lr:beta
    imagePullPolicy: Always
    args: 
    - -l
    - "100"
    - -r
    - -s
    - http://ngsa-cosmos:8080
    - -f
    - benchmark.json
    - --prometheus
    - --zone
    - dev
    - --region
    - dev
