apiVersion: v1
kind: Pod

metadata:
  name: loderunner-benchmark-memory
  labels:
    app: loderunner-benchmark-memory
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'

spec:
  restartPolicy: Always
  containers:
  - name: app
    image: ghcr.io/retaildevcrews/ngsa-lr:beta
    imagePullPolicy: Always
    args: 
    - -l
    - "100"
    - -r
    - -s
    - http://ngsa-memory:8080
    - -f
    - benchmark.json
    - --prometheus
    - --zone
    - dev
    - --region
    - dev
