apiVersion: v1
kind: Pod

metadata:
  name: loderunner
  labels:
    app: loderunner

spec:
  containers:
  - name: app

    image: ghcr.io/retaildevcrews/ngsa-lr:beta
    imagePullPolicy: Always

    args: 
    - -l
    - "1000"
    - --prometheus
    - -r
    - -s
    - http://ngsa-memory:8080
    - -f
    - benchmark.json
    - --zone
    - dev
    - --region
    - dev

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner
  labels:
    app: loderunner
spec:
  type: NodePort
  selector:
    app: loderunner
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
