apiVersion: apps/v1
kind: Deployment
metadata:
  name: logapp
  namespace: logapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: logapp
  template:
    metadata:
      labels:
        app: logapp
        app.kubernetes.io/instance: logapp
    spec:
      containers:
      - name: logapp
        image: ghcr.io/retaildevcrews/logapp:latest
        args:
          - --loop
          - -s 1000
        resources:
          requests:
            cpu: "2000m"
          limits:
            cpu: "2000m"
